project:
  type: website

website:
  title: Charting Constellations
  navbar:
    right:
      - icon: images/constellationlogo.jpg
        href: https://github.com/INFO526-DataViz/project-final-Chart-Champions/
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
