project:
  type: website

website:
  title: Charting Constellations
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-final-Chart-Champions/
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\constellationlogo.png
    favicon: images\constellationlogo.png

format:
  html:
    theme: "pulse"
    toc: true

execute:
  freeze: auto
